version: '3.8'

services: 
  db:
    image: cassandra:latest
    container_name: Cassandra
    hostname: cassandra
    volumes: 
      - cassandra_data:/var/lib/cassandra
    ports:
      - "9042:9042"
    networks:
      - cassandra_net

  cqlsh_setup:
    image: nuvo/docker-cqlsh
    depends_on:
      - db
    volumes:
      - ./data.cql:/scripts/data.cql
    environment:
      CQLSH_HOST: cassandra
      CQLSH_PORT: 9042
      CQLVERSION: 3.4.6
    command: ["sh", "-c", "sleep 30 && cqlsh -f ./data.cql"]
    networks:
      - cassandra_net

  cqlsh_interactive:
    image: nuvo/docker-cqlsh
    depends_on: 
      - db
    environment:
      CQLSH_HOST: cassandra
      CQLSH_PORT: 9042
      CQLVERSION: 3.4.6
    volumes:
      - ./data.cql:/scripts/data.cql
    entrypoint: ["/bin/bash", "-c", "echo 'Connected to Test Cluster at cassandra:9042. Use HELP for help.' && /bin/bash"]
    networks:
      - cassandra_net


networks:
  cassandra_net:
    driver: bridge

volumes:
  cassandra_data:
    driver: local
    
